version: '3'
services:
  mumitroll:
    hostname: mysql
    container_name: mumitroll-container
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mumidalen_db
